### ISSUE TITLE
Unable to load module on m1 mac, reports VLC not found

### ISSUE THREAD

**Issue by steddyman** [Richienb/audic#14]
I am trying to use the Audic module from a nodeJS application running with a commonJS script.  I have managed to get it to load with the following code, but when I try and use it I get the following error, despite haveingVLC installed in the Apps folder and 'brew install vlc' reporting it is already installed.

Code to load it:
    // Load sound library
    Audic = await import('audic')
    Audic.playAudioFile("notification.mp3")

Error in the node console:
node:74697) UnhandledPromiseRejectionWarning: Error: Unable to find a suitable VLC binary for MacOS. Please install VLC.
    at vlcStatic (file:///Users/stepheneddy/Dropbox/Dev/Crypto/NFTBot/node_modules/vlc-static/index.js:39:8)
    at vlcStatic (file:///Users/stepheneddy/Dropbox/Dev/Crypto/NFTBot/node_modules/vlc-static/node_modules/onetime/index.js:18:28)
    at createVlc (file:///Users/stepheneddy/Dropbox/Dev/Crypto/NFTBot/node_modules/@richienb/vlc/dist/index.js:33:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async file:///Users/stepheneddy/Dropbox/Dev/Crypto/NFTBot/node_modules/audic/dist/index.js:89:25
    at async Audic.play (file:///Users/stepheneddy/Dropbox/Dev/Crypto/NFTBot/node_modules/audic/dist/index.js:106:25)

**Comment by Richienb** [comment]
`vlc-static` is not detecting the installation because it doesn't know where to look for the vlc binary. See what happens when you do this: https://superuser.com/questions/997673/how-to-run-vlc-command-in-mac-terminal

<blockquote><img src="https://cdn.sstatic.net/Sites/superuser/Img/apple-touch-icon@2.png?v=e869e4459439" width="48" align="right"><div>Super User</div><div><strong><a href="https://superuser.com/questions/997673/how-to-run-vlc-command-in-mac-terminal">How to run VLC command in mac terminal</a></strong></div><div>I am trying to crop a number of videos using the following vlc terminal command:

vlc input.mp4 --crop=480x270+200+100
However, I am getting the following error:

-bash: vlc: command not found
Ho...</div></blockquote>
