### ISSUE TITLE
RequestError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by nolanbarry** [Richienb/audic#18]
Occasionally when playing a sound I get the following error:
```
.../node_modules/got/dist/source/core/index.js:970                                                                      [92/162]
            error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);                                           
                                                                                                              ^                                                                                       
RequestError: connect ECONNREFUSED 10.37.58.128:49457                                                                                                                                                 
    at ClientRequest.<anonymous> (.../node_modules/got/dist/source/core/index.js:970:111)                                       
    at Object.onceWrapper (node:events:628:26)                                                                                                                                                        
    at ClientRequest.emit (node:events:525:35)                                                                                                                                                        
    at ClientRequest.emit (node:domain:489:12)                                                                                                                                                        
    at ClientRequest.origin.emit (.../node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)                            
    at Socket.socketErrorListener (node:_http_client:488:9)                                                                                                                                           
    at Socket.emit (node:events:513:28)                                                                                                                                                               
    at Socket.emit (node:domain:489:12)                                                                                                                                                               
    at emitErrorNT (node:internal/streams/destroy:151:8)                                                                                                                                              
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)                                                                                                                                         
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1283:16) {                                                                                                                               
  code: 'ECONNREFUSED',                                                                                                                                                                               
  timings: {                                                                                                                                                                                          
    start: 1670520647725,                                                                                                                                                                             
    socket: 1670520647725,                                                                                                                                                                            
    lookup: undefined,                                                                                                                                                                                
    connect: undefined,                                                                                                                                                                               
    secureConnect: undefined,                                                                                                                                                                         
    upload: undefined,                                                                                                                                                                                
    response: undefined,                                                                                                                                                                              
    end: undefined,                              
    error: 1670520647725,                        
    abort: undefined,                            
    phases: {                                    
      wait: 0,                                   
      dns: undefined,                            
      tcp: undefined,                            
      tls: undefined,                            
      request: undefined,                        
      firstByte: undefined,                      
      download: undefined,                       
      total: 0         
    }                                            
  }                                              
}   
```
Running `vlc` in the command line (even `vlc --help`, which doesn't keep a process running in the foreground) and restarting the node process seems to fix it, but I'm wondering if there's a little more insight on what exactly is happening behind the scenes?

**Comment by AbdBarho** [comment]
I managed to reproduce reliably on my machine with this snippet, not sure if it is only my machine or what:

```js
import { playAudioFile } from "audic";

playAudioFile("not.mp3");

setTimeout(() => {
  playAudioFile("not.mp3");
}, 5000);
```

The audio file is only 3 seconds

**Comment by Richienb** [comment]
The issue probably resides here: https://github.com/Richienb/vlc/blob/45eedbf9bab5e8985e6b32f1d9217c3e8a368c0a/source/index.ts#L190
A possible cause could be that it tries to connect to vlc while it is still starting the server so it fails.

**Comment by AbdBarho** [comment]
@Richienb using your `vlc` library directly solves the problem for me (ignore ugly nesting):

```js

import createVlc from "@richienb/vlc";

const vlc = await createVlc();

const play = () => vlc.command("in_play", { input: "not.mp3" });

play();

setTimeout(() => {
  play();
  setTimeout(() => {
    vlc.kill();
  }, 5000);
}, 5000);
```

**Comment by Richienb** [comment]
The first `setTimeout` in your example supports the hypothesis that the http request is being made too early in the codebase of audic.
Not sure how to fix it well, PR welcome.

**Comment by nolanbarry** [comment]
I ended up creating my own VLC wrapper (needed video playback anyway), which uses a request queue to send requests only after a successful ping to VLC. That'd require changing how this library works in a big way so ditto on the no easy fix. Could perhaps just make the constructor private and add a static async function that returns the VLC instance once it's established that it is accepting connections?

**Comment by Richienb** [comment]
The solution is to probably change the upstream library https://github.com/Richienb/vlc instead.

**Comment by jorisvilardell** [comment]
Hello same problem, my server crash and it's happened randomly I can't do anythings (I can just pray that will not crash anymore). If you want I can make a contribution but I need an explanation about how audic works. I tried to look your dependencies, I understood you use VLC socket api to control the VLC player. Is it possible to replace the use of a socket by the use of VLC commands ?

```ts
import { exec } from 'child_process';

class VLCPlayer {
  private vlcPath: string;

  constructor(vlcPath: string = 'vlc') {
    this.vlcPath = vlcPath;
  }

  public play(filePath: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const command = `${this.vlcPath} --intf dummy "${filePath}" vlc://quit`;
      exec(command, (error, stdout, stderr) => {
        if (error) {
          console.error(`Error playing file: ${stderr}`);
          reject(error);
        } else {
          console.log(`Playing file: ${stdout}`);
          resolve();
        }
      });
    });
  }
}

// Exemple of use
const player = new VLCPlayer();
player.play('/path/to/your/audio/file.mp3')
  .then(() => console.log('Playback finished'))
  .catch((error) => console.error('Error during playback:', error));
  ```

**Comment by piemadd** [comment]
I was having this issue after I had installed `vlc-bin` via apt. I ended up installing `vlc` with snap and that fixed the issue for me. Running Zorin OS 17.3 (based on Ubuntu 22.04 LTS). I'm not sure if this is the issue others are facing, but presumably `vlc-bin` is broken and is the root of the issues experienced.
